# Generated by Django 4.2 on 2023-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_mad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='music',
            new_name='artistname',
        ),
        migrations.AddField(
            model_name='music',
            name='file',
            field=models.FileField(default=1, upload_to='music'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='musicname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
