# Generated by Django 4.2 on 2023-04-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_mad', '0002_rename_music_music_artistname_music_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsname', models.CharField(max_length=300)),
                ('adsimg', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='musicimg',
            field=models.ImageField(default='test', upload_to='image'),
            preserve_default=False,
        ),
    ]
