# Generated by Django 4.2 on 2023-04-29 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_mad', '0004_freebeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='freebeat',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 4, 29, 9, 51, 46, 943805)),
        ),
        migrations.AddField(
            model_name='music',
            name='created',
            field=models.TimeField(default=datetime.datetime(2023, 4, 29, 9, 51, 46, 943805)),
        ),
    ]
